# Generated by Django 2.2.2 on 2019-06-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerShakeWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChromeExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOI', models.IntegerField()),
                ('genComments', models.TextField()),
                ('specComments', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
