# Generated by Django 2.2.2 on 2019-06-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerShakeWeb', '0002_chromeextension'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chromeextension',
            old_name='genComments',
            new_name='genComment',
        ),
        migrations.RenameField(
            model_name='chromeextension',
            old_name='specComments',
            new_name='specComment',
        ),
        migrations.AlterField(
            model_name='chromeextension',
            name='DOI',
            field=models.CharField(max_length=50),
        ),
    ]
