# Generated by Django 2.2.2 on 2019-06-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerShakeWeb', '0003_auto_20190606_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chromeextension',
            name='DOI',
        ),
        migrations.AddField(
            model_name='chromeextension',
            name='paperTitleCE',
            field=models.TextField(default=''),
        ),
    ]
