# Generated by Django 2.2.2 on 2019-06-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerShakeWeb', '0004_auto_20190606_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chromeextension',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='chromeextension',
            name='genComment',
            field=models.TextField(verbose_name='General Comments'),
        ),
        migrations.AlterField(
            model_name='chromeextension',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='chromeextension',
            name='paperTitleCE',
            field=models.TextField(default='', verbose_name='Paper Title'),
        ),
        migrations.AlterField(
            model_name='chromeextension',
            name='specComment',
            field=models.TextField(verbose_name='Specific Comments'),
        ),
    ]
