# Generated by Django 2.2.2 on 2019-06-10 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PeerShakeWeb', '0005_auto_20190607_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='chromeextension',
            name='doi',
            field=models.IntegerField(default=0, verbose_name='DOI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chromeextension',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='Url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chromeextension',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
    ]
