# Generated by Django 2.2.2 on 2019-06-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerShakeWeb', '0006_auto_20190610_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chromeextension',
            name='doi',
            field=models.CharField(max_length=100, verbose_name='DOI'),
        ),
    ]
